kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile-template
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: check-test-app
          user: admin
          lifetimeMinutes: "3"
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: prometheusverification
          globalLogTemplate: logtemp
          services:
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},check-test-app"
            canaryMetricScope: "argocd,{{args.canary-hash}},check-test-app"
            metricTemplateName: "PrometheusMetricTemplate"
          - metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "argocd,{{args.baseline-hash}}"
            canaryMetricScope: "argocd,{{args.canary-hash}}"
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
