kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis-ta
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis-ta
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile
          application: apptest
          gateUrl: https://isdokta.argo.ninja-test.opsmx.org/
          user: admin
          intervalTime: 6
          lookBackType: growing
          lifetimeMinutes: 30
          threshold:
            pass: 90
            marginal: 65
          services:
          - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},demoapp-issuegen-ta"
            canaryMetricScope: "argocd,{{args.canary-hash}},demoapp-issuegen-ta"
            metricTemplateName: "PrometheusMetricTemplate" 
