apiVersion: v1
kind: ConfigMap
metadata:
  name: analysis-temp-opsmx
data:
  providerConfig: |
    application: opsmx-job-ta
    user: admin
    gateUrl: 'https://isd-dev.argo-dev.opsmx.net/'
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: true
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${service},${ingress}"
      baselineMetricScope: "argocd,rollout-demo-active,rollout-demo-active"
      canaryMetricScope: "argocd,rollout-demo-preview,rollout-demo-preview"
      metricTemplateName: "prometheus-nginx-ingress-metric-template"
    - logTemplateName: log-yaml-data
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
