apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: job-analysis-new
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: job-analysis-new
  template:
    metadata:
      labels:
        app: job-analysis-new
    spec:
      containers:
      - name: rollouts-demo
        image: docker.io/opsmxdev/issuegen:v3.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: rollout-demo-active
      previewService: rollout-demo-preview
      autoPromotionSeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: job-analysis-new
        args:
        - name: baseline-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: preview-hash
          valueFrom:
            podTemplateHashValue: Latest
      autoPromotionEnabled: false
      postPromotionAnalysis:
        templates:
        - templateName: job-analysis-new
        args:
        - name: baseline-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: preview-hash
          valueFrom:
            podTemplateHashValue: Latest
