apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argotest-sservice
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argotest-sservice
  template:
    metadata:   
      labels:
        app: argotest-sservice
    spec:
      containers:
        - name: rollouts-demo-exp
          image: docker.io/opsmxdev/issuegen:v3.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:     
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 10s }
        - analysis:
            templates:
              - templateName: application-test-ta
            args:
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: baseline-hash
                valueFrom:
                  podTemplateHashValue: Stable            
            
