kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: application-test-ta
spec:
  metrics:
    - name: application-test-ta
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          application: application-test-ta
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricScopeVariables: "${namespace_key},${app_name}"
            baselineMetricScope: "argocd,application-test-ta"
            canaryMetricScope: "argocd,application-test-ta"
            metricTemplateName: PrometheusMetricTemplate
