kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo-newrelic-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: demo-newrelic-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile-v3
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: newrelicregexapp
          user: admin
          lifetimeMinutes: 6
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: newrelicregextemplate
            metricScopeVariables: "app_key,pod_key"
            baselineMetricScope: "demo-test,{{args.baseline-hash}}"
            canaryMetricScope: "demo-test,{{args.canary-hash}}"
